### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JanX2** [chandansingh5/CSVideoPlayer#1]
I couldn’t find any mention of a license. What’s license for this project?

**Comment by chandansingh5** [comment]
@JanX2 Added

**Comment by JanX2** [comment]
Thanks!

**Comment by JanX2** [comment]
GPL3 prevents this code from being used for any App Store projects. Is that deliberate?

**Comment by chandansingh5** [comment]
@JanX2 change license to MIT.

**Comment by JanX2** [comment]
Thanks for sharing. :)
